/*

 Copyright 2015 Google Inc. All Rights Reserved.

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
*/
var componentHandler={upgradeDom:function(){},upgradeElement:function(){},upgradeElements:function(){},upgradeAllRegistered:function(){},registerUpgradedCallback:function(){},register:function(){},downgradeElements:function(){}},componentHandler=function(){function findRegisteredClass_(name,optReplace){for(var i=0;i<registeredComponents_.length;i++)if(registeredComponents_[i].className===name)return"undefined"!==typeof optReplace&&(registeredComponents_[i]=optReplace),registeredComponents_[i];return!1}
function getUpgradedListOfElement_(element){var dataUpgraded=element.getAttribute("data-upgraded");return null===dataUpgraded?[""]:dataUpgraded.split(",")}function isElementUpgraded_(element,jsClass){var upgradedList=getUpgradedListOfElement_(element);return-1!==upgradedList.indexOf(jsClass)}function upgradeDomInternal(optJsClass,optCssClass){if("undefined"===typeof optJsClass&&"undefined"===typeof optCssClass)for(var i=0;i<registeredComponents_.length;i++)upgradeDomInternal(registeredComponents_[i].className,
registeredComponents_[i].cssClass);else{var jsClass=optJsClass;if("undefined"===typeof optCssClass){var registeredClass=findRegisteredClass_(jsClass);registeredClass&&(optCssClass=registeredClass.cssClass)}for(var elements=document.querySelectorAll("."+optCssClass),n=0;n<elements.length;n++)upgradeElementInternal(elements[n],jsClass)}}function upgradeElementInternal(element,optJsClass){if(!("object"===typeof element&&element instanceof Element))throw Error("Invalid argument provided to upgrade MDL element.");
var upgradedList=getUpgradedListOfElement_(element),classesToUpgrade=[];if(optJsClass)isElementUpgraded_(element,optJsClass)||classesToUpgrade.push(findRegisteredClass_(optJsClass));else{var classList=element.classList;registeredComponents_.forEach(function(component){classList.contains(component.cssClass)&&-1===classesToUpgrade.indexOf(component)&&!isElementUpgraded_(element,component.className)&&classesToUpgrade.push(component)})}for(var i=0,n=classesToUpgrade.length,registeredClass;i<n;i++){if(registeredClass=
classesToUpgrade[i]){upgradedList.push(registeredClass.className);element.setAttribute("data-upgraded",upgradedList.join(","));var instance=new registeredClass.classConstructor(element);instance.mdlComponentConfigInternal_=registeredClass;createdComponents_.push(instance);for(var j=0,m=registeredClass.callbacks.length;j<m;j++)registeredClass.callbacks[j](element);registeredClass.widget&&(element[registeredClass.className]=instance)}else throw Error("Unable to find a registered component for the given class.");
var ev;"CustomEvent"in window&&"function"===typeof window.CustomEvent?ev=new Event("mdl-componentupgraded",{bubbles:!0,cancelable:!1}):(ev=document.createEvent("Events"),ev.initEvent("mdl-componentupgraded",!0,!0));element.dispatchEvent(ev)}}function upgradeElementsInternal(elements){Array.isArray(elements)||(elements=elements instanceof Element?[elements]:Array.prototype.slice.call(elements));for(var i=0,n=elements.length,element;i<n;i++)element=elements[i],element instanceof HTMLElement&&(upgradeElementInternal(element),
0<element.children.length&&upgradeElementsInternal(element.children))}function registerInternal(config){var widgetMissing="undefined"===typeof config.widget&&"undefined"===typeof config.widget,widget=!0;widgetMissing||(widget=config.widget||config.widget);var newConfig={classConstructor:config.constructor||config.constructor,className:config.classAsString||config.classAsString,cssClass:config.cssClass||config.cssClass,widget:widget,callbacks:[]};registeredComponents_.forEach(function(item){if(item.cssClass===
newConfig.cssClass)throw Error("The provided cssClass has already been registered: "+item.cssClass);if(item.className===newConfig.className)throw Error("The provided className has already been registered");});if(config.constructor.prototype.hasOwnProperty("mdlComponentConfigInternal_"))throw Error("MDL component classes must not have mdlComponentConfigInternal_ defined as a property.");var found=findRegisteredClass_(config.classAsString,newConfig);found||registeredComponents_.push(newConfig)}function registerUpgradedCallbackInternal(jsClass,
callback){var regClass=findRegisteredClass_(jsClass);regClass&&regClass.callbacks.push(callback)}function upgradeAllRegisteredInternal(){for(var n=0;n<registeredComponents_.length;n++)upgradeDomInternal(registeredComponents_[n].className)}function deconstructComponentInternal(component){if(component){var componentIndex=createdComponents_.indexOf(component);createdComponents_.splice(componentIndex,1);var upgrades=component.element_.getAttribute("data-upgraded").split(","),componentPlace=upgrades.indexOf(component.mdlComponentConfigInternal_.classAsString);
upgrades.splice(componentPlace,1);component.element_.setAttribute("data-upgraded",upgrades.join(","));var ev;"CustomEvent"in window&&"function"===typeof window.CustomEvent?new Event("mdl-componentdowngraded",{bubbles:!0,cancelable:!1}):(ev=document.createEvent("Events"),ev.initEvent("mdl-componentdowngraded",!0,!0))}}function downgradeNodesInternal(nodes){var downgradeNode=function(node){createdComponents_.filter(function(item){return item.element_===node}).forEach(deconstructComponentInternal)};
if(nodes instanceof Array||nodes instanceof NodeList)for(var n=0;n<nodes.length;n++)downgradeNode(nodes[n]);else if(nodes instanceof Node)downgradeNode(nodes);else throw Error("Invalid argument provided to downgrade MDL nodes.");}var registeredComponents_=[],createdComponents_=[];return{upgradeDom:upgradeDomInternal,upgradeElement:upgradeElementInternal,upgradeElements:upgradeElementsInternal,upgradeAllRegistered:upgradeAllRegisteredInternal,registerUpgradedCallback:registerUpgradedCallbackInternal,
register:registerInternal,downgradeElements:downgradeNodesInternal}}();componentHandler.upgradeDom=componentHandler.upgradeDom;componentHandler.upgradeElement=componentHandler.upgradeElement;componentHandler.upgradeElements=componentHandler.upgradeElements;componentHandler.upgradeAllRegistered=componentHandler.upgradeAllRegistered;componentHandler.registerUpgradedCallback=componentHandler.registerUpgradedCallback;componentHandler.register=componentHandler.register;
componentHandler.downgradeElements=componentHandler.downgradeElements;window.componentHandler=componentHandler;window.componentHandler=componentHandler;window.addEventListener("load",function(){"classList"in document.createElement("div")&&"querySelector"in document&&"addEventListener"in window&&Array.prototype.forEach?(document.documentElement.classList.add("mdl-js"),componentHandler.upgradeAllRegistered()):(componentHandler.upgradeElement=function(){},componentHandler.register=function(){})});(function(){var MaterialButton=function(element){this.element_=element;this.init()};window.MaterialButton=MaterialButton;MaterialButton.prototype.Constant_={};MaterialButton.prototype.CssClasses_={RIPPLE_EFFECT:"mdl-js-ripple-effect",RIPPLE_CONTAINER:"mdl-button__ripple-container",RIPPLE:"mdl-ripple"};MaterialButton.prototype.blurHandler_=function(event){event&&this.element_.blur()};MaterialButton.prototype.disable=function(){this.element_.disabled=!0};MaterialButton.prototype.disable=MaterialButton.prototype.disable;
MaterialButton.prototype.enable=function(){this.element_.disabled=!1};MaterialButton.prototype.enable=MaterialButton.prototype.enable;MaterialButton.prototype.init=function(){if(this.element_){if(this.element_.classList.contains(this.CssClasses_.RIPPLE_EFFECT)){var rippleContainer=document.createElement("span");rippleContainer.classList.add(this.CssClasses_.RIPPLE_CONTAINER);this.rippleElement_=document.createElement("span");this.rippleElement_.classList.add(this.CssClasses_.RIPPLE);rippleContainer.appendChild(this.rippleElement_);
this.boundRippleBlurHandler=this.blurHandler_.bind(this);this.rippleElement_.addEventListener("mouseup",this.boundRippleBlurHandler);this.element_.appendChild(rippleContainer)}this.boundButtonBlurHandler=this.blurHandler_.bind(this);this.element_.addEventListener("mouseup",this.boundButtonBlurHandler);this.element_.addEventListener("mouseleave",this.boundButtonBlurHandler)}};componentHandler.register({constructor:MaterialButton,classAsString:"MaterialButton",cssClass:"mdl-js-button",widget:!0})})();(function(){var MaterialProgress=function(element){this.element_=element;this.init()};window.MaterialProgress=MaterialProgress;MaterialProgress.prototype.Constant_={};MaterialProgress.prototype.CssClasses_={INDETERMINATE_CLASS:"mdl-progress__indeterminate"};MaterialProgress.prototype.setProgress=function(p){this.element_.classList.contains(this.CssClasses_.INDETERMINATE_CLASS)||(this.progressbar_.style.width=p+"%")};MaterialProgress.prototype.setProgress=MaterialProgress.prototype.setProgress;MaterialProgress.prototype.setBuffer=
function(p){this.bufferbar_.style.width=p+"%";this.auxbar_.style.width=100-p+"%"};MaterialProgress.prototype.setBuffer=MaterialProgress.prototype.setBuffer;MaterialProgress.prototype.init=function(){if(this.element_){var el=document.createElement("div");el.className="progressbar bar bar1";this.element_.appendChild(el);this.progressbar_=el;el=document.createElement("div");el.className="bufferbar bar bar2";this.element_.appendChild(el);this.bufferbar_=el;el=document.createElement("div");el.className=
"auxbar bar bar3";this.element_.appendChild(el);this.auxbar_=el;this.progressbar_.style.width="0%";this.bufferbar_.style.width="100%";this.auxbar_.style.width="0%";this.element_.classList.add("is-upgraded")}};componentHandler.register({constructor:MaterialProgress,classAsString:"MaterialProgress",cssClass:"mdl-js-progress",widget:!0})})();/*

 Copyright (c) 2011 Erik M?ller, Paul Irish, Tino Zijdel; Licensed MIT http://opensource.org/licenses/MIT
 http://paulirish.com/2011/requestanimationframe-for-smart-animating/
 http://my.opera.com/emoller/blog/2011/12/20/requestanimationframe-for-smart-er-animating
 requestAnimationFrame polyfill by Erik M?ller. fixes from Paul Irish and Tino Zijdel
*/
(function(){for(var lastTime=0,vendors=["ms","moz","webkit","o"],x=0;x<vendors.length&&!window.requestAnimationFrame;++x)window.requestAnimationFrame=window[vendors[x]+"RequestAnimationFrame"],window.cancelAnimationFrame=window[vendors[x]+"CancelAnimationFrame"]||window[vendors[x]+"CancelRequestAnimationFrame"];window.requestAnimationFrame||(window.requestAnimationFrame=function(callback){var currTime=(new Date).getTime(),timeToCall=Math.max(0,16-(currTime-lastTime)),id=window.setTimeout(function(){callback(currTime+
timeToCall)},timeToCall);lastTime=currTime+timeToCall;return id});window.cancelAnimationFrame||(window.cancelAnimationFrame=function(id){clearTimeout(id)})})();(function(){var MaterialRipple=function(element){this.element_=element;this.init()};window.MaterialRipple=MaterialRipple;MaterialRipple.prototype.Constant_={INITIAL_SCALE:"scale(0.0001, 0.0001)",INITIAL_SIZE:"1px",INITIAL_OPACITY:"0.4",FINAL_OPACITY:"0",FINAL_SCALE:""};MaterialRipple.prototype.CssClasses_={RIPPLE_CENTER:"mdl-ripple--center",RIPPLE_EFFECT_IGNORE_EVENTS:"mdl-js-ripple-effect--ignore-events",RIPPLE:"mdl-ripple",IS_ANIMATING:"is-animating",IS_VISIBLE:"is-visible"};MaterialRipple.prototype.downHandler_=
function(event){if(!this.rippleElement_.style.width&&!this.rippleElement_.style.height){var rect=this.element_.getBoundingClientRect();this.boundHeight=rect.height;this.boundWidth=rect.width;this.rippleSize_=2*Math.sqrt(rect.width*rect.width+rect.height*rect.height)+2;this.rippleElement_.style.width=this.rippleSize_+"px";this.rippleElement_.style.height=this.rippleSize_+"px"}this.rippleElement_.classList.add(this.CssClasses_.IS_VISIBLE);if("mousedown"===event.type&&this.ignoringMouseDown_)this.ignoringMouseDown_=
!1;else{"touchstart"===event.type&&(this.ignoringMouseDown_=!0);var frameCount=this.frameCount_;if(!(0<frameCount)){this.setFrameCount(1);var bound=event.currentTarget.getBoundingClientRect(),x,y;if(0===event.clientX&&0===event.clientY)x=Math.round(bound.width/2),y=Math.round(bound.height/2);else{var clientX=event.clientX?event.clientX:event.touches[0].clientX,clientY=event.clientY?event.clientY:event.touches[0].clientY;x=Math.round(clientX-bound.left);y=Math.round(clientY-bound.top)}this.setRippleXY(x,
y);this.setRippleStyles(!0);window.requestAnimationFrame(this.animFrameHandler.bind(this))}}};MaterialRipple.prototype.upHandler_=function(event){event&&2!==event.detail&&window.setTimeout(function(){this.rippleElement_.classList.remove(this.CssClasses_.IS_VISIBLE)}.bind(this),0)};MaterialRipple.prototype.init=function(){if(this.element_){var recentering=this.element_.classList.contains(this.CssClasses_.RIPPLE_CENTER);this.element_.classList.contains(this.CssClasses_.RIPPLE_EFFECT_IGNORE_EVENTS)||
(this.rippleElement_=this.element_.querySelector("."+this.CssClasses_.RIPPLE),this.y_=this.x_=this.rippleSize_=this.frameCount_=0,this.ignoringMouseDown_=!1,this.boundDownHandler=this.downHandler_.bind(this),this.element_.addEventListener("mousedown",this.boundDownHandler),this.element_.addEventListener("touchstart",this.boundDownHandler),this.boundUpHandler=this.upHandler_.bind(this),this.element_.addEventListener("mouseup",this.boundUpHandler),this.element_.addEventListener("mouseleave",this.boundUpHandler),
this.element_.addEventListener("touchend",this.boundUpHandler),this.element_.addEventListener("blur",this.boundUpHandler),this.setFrameCount=function(fC){this.frameCount_=fC},this.setRippleXY=function(newX,newY){this.x_=newX;this.y_=newY},this.setRippleStyles=function(start){if(null!==this.rippleElement_){var transformString,scale,offset="translate("+this.x_+"px, "+this.y_+"px)";start?scale=this.Constant_.INITIAL_SCALE:(scale=this.Constant_.FINAL_SCALE,recentering&&(offset="translate("+this.boundWidth/
2+"px, "+this.boundHeight/2+"px)"));transformString="translate(-50%, -50%) "+offset+scale;this.rippleElement_.style.webkitTransform=transformString;this.rippleElement_.style.msTransform=transformString;this.rippleElement_.style.transform=transformString;start?this.rippleElement_.classList.remove(this.CssClasses_.IS_ANIMATING):this.rippleElement_.classList.add(this.CssClasses_.IS_ANIMATING)}},this.animFrameHandler=function(){0<this.frameCount_--?window.requestAnimationFrame(this.animFrameHandler.bind(this)):
this.setRippleStyles(!1)})}};componentHandler.register({constructor:MaterialRipple,classAsString:"MaterialRipple",cssClass:"mdl-js-ripple-effect",widget:!1})})();
